### ISSUE TITLE
Is there a list of the possible mods for this port

### ISSUE THREAD

**Issue by Erwandawa123** [TurtleHouse/PizzaTowerSwitch-FMOD#16]
I have nothing else to do

**Comment by Erwandawa123** [comment]
In pizza tower I mean

**Comment by TurtleHouse** [comment]
anything is possible if you put your heart in it!

![image](https://github.com/TurtleHouse/PizzaTowerSwitch-FMOD/assets/87158297/46d7941a-6158-4d35-8f69-6686f7c1bdeb)
