### ISSUE TITLE
Could you add CYOP?

### ISSUE THREAD

**Issue by urnewjellyfish** [TurtleHouse/PizzaTowerSwitch-FMOD#19]
I see how the port connects to wifi so I was wondering if you could add the create your own pizza mod so we can play infinite levels you can also add ptu and other stuff.

**Comment by TurtleHouse** [comment]
PTU definitely not, but the developer can look into CYOP, depending on how easy it would be

**Comment by Erwandawa123** [comment]
How would we even import levels to cyop?
