### ISSUE TITLE
Are there plans for more unofficial ports? 

### ISSUE THREAD

**Issue by MetalMaxMX** [TurtleHouse/PizzaTowerSwitch-FMOD#2]
I understand that this repo wants to be primarily aimed at issues with the unofficial Switch port of this game already released through the tinfoil shops. However, I just want to know if this knowledge and info is only going to remain for the Switch port or if there are any plans to do ports to other platforms that GM supports? (Like Sony's consoles, MS' ones or even other OSes like macOS or Linux)

**Comment by TurtleHouse** [comment]
the switch port dev isn't interested but if anyone else is they can use the code provided

**Comment by Spider-Sonic** [comment]
Hello!
Is it possible to port this to the Nintendo Wii U and 3DS? Not asking for anyone to port it.

Thanks!

**Comment by TurtleHouse** [comment]
@Spider-Sonic Any platform which gamemaker can export to, pizza tower could be ported easily. However, none of those platforms are the ones you mentioned.

all of these platforms are possible though: 
![image](https://github.com/TurtleHouse/PizzaTowerSwitch-FMOD/assets/87158297/4e78f567-c628-483f-801f-117a2d608fa4)

**Comment by HeckGarbage** [comment]
Can you make an android port? My switch cant be jailbreaked since its fixed.

**Comment by D-Official** [comment]
> Can you make an android port? My switch cant be jailbreaked since its fixed.

There are two Android ports out already; one is a port of this Switch port, and the other was made separately. I can attest that both are quality ports. I can't link them, but you should be able to find both by searching them up.
