### ISSUE TITLE
Potential ports to other consoles?

### ISSUE THREAD

**Issue by Spider-Sonic** [TurtleHouse/PizzaTowerSwitch-FMOD#3]
Hello, 
As someone who owns multiple consoles and love Pizza Tower, I was wondering if it were possible for a port of this game to other consoles? (i.e. Wii U, PlayStation 3, 3DS, etc...) 
Now, I'm not assigning work to anyone. I just wanna know if it is possible to port it to other consoles. That's all!

Thanks!

**Comment by TurtleHouse** [comment]
https://github.com/TurtleHouse/PizzaTowerSwitch-FMOD/issues/2
