### ISSUE TITLE
Plans to add future updates to port.

### ISSUE THREAD

**Issue by Dededeez** [TurtleHouse/PizzaTowerSwitch-FMOD#35]
Do you have any plans on continuing to update this project as future content updates for Pizza Tower release, such as the Halloween update that released today?

**Comment by D-Official** [comment]
As updating the port to a new Pizza Tower version is a difficult process, I prefer to do it as little as possible, which is why I am holding off from doing it until 1 or 2 bug fixing patches come. Until then, or until enough time without an update has passed, nothing will be done.

**Comment by Dededeez** [comment]
Understandable, thanks for keeping us all updated on the project.
