### ISSUE TITLE
Invalid NCA Signature

### ISSUE THREAD

**Issue by Bossiskeyboard** [TurtleHouse/PizzaTowerSwitch-FMOD#43]
![Screenshot 2024-01-10 121739](https://github.com/TurtleHouse/PizzaTowerSwitch-FMOD/assets/120620395/f5857377-a773-4202-8976-90d8ac95baee)

**Comment by D-Official** [comment]
The NCA signature is only valid for official titles. This port is unofficial homebrew.

**Comment by Bossiskeyboard** [comment]
oh, alright. thanks for the response.
