### ISSUE TITLE
How do I update my mobile port?

### ISSUE THREAD

**Issue by The-weird-guy** [TurtleHouse/PizzaTowerSwitch-FMOD#51]
I've been wondering how do I update my mobile port by "D" since I don't have the current version. (in the about section it said to go to this link for any help.)

**Comment by D-Official** [comment]
I did not make the Android port. Someone else ported my Switch port to Android, while keeping the update checker. So it does say there's an update, but it's really for the Switch port.

**Comment by The-weird-guy** [comment]
Thank you for informing me that you didn't make that android port and it was a port of your port D-Official.
