### ISSUE TITLE
save file swapping

### ISSUE THREAD

**Issue by OrdinaryGP** [TurtleHouse/PizzaTowerSwitch-FMOD#7]
not exactly an issue but I cant find the save files for pizza tower on switch and I wanna swap the save file to be my pc save. would that be possible?

**Comment by OrdinaryGP** [comment]
[saves.zip](https://github.com/TurtleHouse/PizzaTowerSwitch-FMOD/files/11620725/saves.zip)
the first save in particular I wanna put on my switch

**Comment by TurtleHouse** [comment]
Yes, this works, just import the save using any save manager.
